[package]
name = "akl"
version = "0.1.0"
edition = "2021"

[dependencies]
hidapi = "2.6.1"
sysinfo = "0.30.13"
libappindicator = "0.9.0"
image = "0.25.1"
gtk = "0.18.1"
tokio = { version = "1", features = ["full"] }